name: Ejemplo de uso de Servicios Docker

on: [push]

# https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/accessing-contextual-information-about-workflow-runs#vars-context

env:
  # Setting an environment variable with the value of a CONFIGURATION variable
  # (CONFIGURATION variable): github gh-username/repo-name > Settings > Secrets and variables > Actions
  oracle_db_url: ${{ vars.DEV_ENV_ORACLE_DB_URL }}

jobs:
  docker-services-job:
    # Specific GH-Environment for this job
    environment: development-env
    runs-on: ubuntu-latest

    # Variables de entorno para el workflow
    env:
      MY_VAR: Mi variable de entorno

    # Docker services (MySQL, Redis, etc.)
    services:
      mysql:
        image: mysql:5.7
        env:
          # The password TO BE set for the MySQL root user
          MYSQL_ROOT_PASSWORD: example101
        ports:
          - 3306:3306

      redis:
        image: redis:latest
        ports:
          - 6379:6379
    
    steps:
      - name: Listar directorio de trabajo
        run: ls -al

      - name: Impresión de variable de entorno
        env:
          MY_VAR_STEP: Variable a Nivel de Step
        # Evitar el uso de colon (:) dentro del comando [echo]
        run: | 
          echo "La variable de entorno es [$MY_VAR]"
          echo "La variable de entorno a nivel de step es [$MY_VAR_STEP]"

      - name: Impresión de URL de conexión a la base de datos Oracle
        # {vars.MONGO_BD_URL} is a variable set in the repository settings (repository-variable)
        # {vars.POSTGRESQL_DB_URL} AND {vars.DEV_ENV_ORACLE_DB_URL} are [Environment variables] for the env: [development-env]
        run: |
          echo "La URL de conexión a la base de datos Oracle es [${{ env.oracle_db_url }}]"
          echo "La URL de conexión a la bd PostgreSQL es [${{ vars.POSTGRESQL_DB_URL }}]"
          echo "URL de mongoDB es [${{ vars.MONGO_BD_URL }}]"

      - name: Mostrar valores de SECRETS
        run: |
          echo "El valor del Secret [ORCL_DB_PWD_SECRET] es [${{ secrets.ORCL_DB_PWD_SECRET }}]"
          echo "El valor del Secret [MONGO_DB_PWD_SECRET] es [${{ secrets.MONGO_DB_PWD_SECRET }}]"

      - name: Uso de SSH Public Key (Secret)
        # (127.0.1.1) : localhost
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PUBLIC_KEY }}" >> ~/.ssh/id_rsa.pub
          chmod 600 ~/.ssh/id_rsa.pub
          ssh-keyscan -H 127.0.1.1 >> ~/.ssh/known_hosts
          cat ~/.ssh/known_hosts