name: Ejemplo de uso de Servicios Docker

on: [push]

jobs:
  docker-services-job:
    runs-on: ubuntu-latest

    # Variables de entorno para el workflow
    env:
      MY_VAR: Mi variable de entorno

    # Docker services (MySQL, Redis, etc.)
    services:
      mysql:
        image: mysql:5.7
        env:
          # The password TO BE set for the MySQL root user
          MYSQL_ROOT_PASSWORD: example101
        ports:
          - 3306:3306

      redis:
        image: redis:latest
        ports:
          - 6379:6379
    
    steps:
      - name: Listar directorio de trabajo
        run: ls -al

      - name: Impresión de variable de entorno
        env:
          MY_VAR_STEP: Variable a Nivel de Step
        # Evitar el uso de colon (:) dentro del comando [echo]
        run: | 
          echo "La variable de entorno es [$MY_VAR]"
          echo "La variable de entorno a nivel de step es [$MY_VAR_STEP]"